# Generated by Django 4.1 on 2022-08-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
